name: 'Bielu Aspire Github Actions'
description: 'This actions simplify working with aspire on github actions'

branding:
  icon: "upload-cloud"
  color: "blue"

inputs:
  action:
    description: "Action to perform: install or publish."
    required: true
    default: "install"

  project:
    description: "The Aspire project name or path to publish."
    required: false
    default: ""

  output:
    description: "The output path for publish artifacts."
    required: false
    default: ""

  debug:
    description: "Enable debug mode (true/false)."
    required: false
    default: "false"

  build-configuration:
    description: "The build configuration (e.g., Release or Debug)."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Run Aspire Script
      run: |
        if [ "$RUNNER_OS" = "Windows" ]; then
          pwsh "${{ github.action_path }}\action.ps1" -Action "${{ inputs.action }}"
        else
          bash "${{ github.action_path }}/action.sh" "${{ inputs.action }}"
        fi
      shell: bash
      env:
        PROJECT: "${{ inputs.project }}"
        OUTPUT: "${{ inputs.output }}"
        DEBUG: "${{ inputs.debug }}"
        BUILD_CONFIGURATION: "${{ inputs.build-configuration }}"
