name: 'Bielu Aspire Github Actions'
description: 'This actions simplify working with aspire on github actions'

branding:
  icon: "lock"
  color: "blue"

inputs:
  action:
    description: "Action to perform with aspire i.e Install (installs aspire cli), Publish (publishes project)"
    required: true
  project:
    description: "The path to the Aspire AppHost project file."
    required: false
  output:
    description: "The output path for the generated artifacts. Defaults to './aspire-output' if not specified."
    default: "'./aspire-outpu"
  debug:
    description: "Enable debug logging to the console."
    required: false
    default: "false"
  buildConfiguration:
    description: "Dotnet build configuraiton e.i Release, Debug."
    required: false
    default: "Release"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pwsh "${{ github.action_path }}\\action.ps1"
        else
          bash ${{ github.action_path }}/action.sh
        fi
      env:
        action: "${{inputs.action}}"
        DOTNET_NOLOGO: "1"
