name: 'Bielu Aspire Github Actions'
description: 'This actions simplify working with aspire on github actions'

branding:
  icon: "lock"
  color: "blue"

inputs:
  action:
    description: "Action to perform with aspire i.e Install (installs aspire cli), Publish (publishes project)"
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          pwsh "${{ github.action_path }}\\action.ps1"
        else
          bash ${{ github.action_path }}/action.sh
        fi
      env:
        action: "${{inputs.action}}"
        DOTNET_NOLOGO: "1"
